version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-ranking-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: ranking
      DB_USER: root
      DB_PASS: root
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: tecnofit_db
    environment:
      MYSQL_ROOT_PASSWORD: feofiloff
      MYSQL_DATABASE: tecnofit_database
    volumes:
      - db_data:/var/lib/mysql
      - ./tecnofit_database.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  db_data: